name: "Elapsed Time"
description: "Print how many seconds have elapsed since the last call"

inputs:
  statement:
    description: "Statement to print"
    required: true

  reference:
    description: "Optional unique name for the timestamp file"
    required: false
    default: "generic"

runs:
  using: "composite"
  steps:
    - name: Elapsed Time
      id: elapsed
      shell: bash
      run: |
        FILE=".elapsed_time_${{ inputs.reference }}"

        # 1) Read previous timestamp if present
        if [ -f "$FILE" ]; then
          last_time="$(cat "$FILE")"
        else
          last_time=""
        fi

        # 2) Get current time
        current_time=$(date +%s)

        # 3) Calculate the delta
        if [ -z "$last_time" ]; then
          delta=0
        else
          delta=$(( current_time - last_time ))
        fi

        # 4) Append the result to a "report" file
        # so we can show them all at once at the end.
        echo "${{ inputs.statement }}: ${delta}" >> .elapsed_report

        # 5) Write new timestamp
        echo "$current_time" > "$FILE"
