repos:
  - repo: local
    hooks:
      # Rustfmt formatting check
      - id: rustfmt
        name: Rustfmt
        language: system
        entry: rustfmt
        args: ["--edition", "2024", "--check"]
        pass_filenames: true
        files: \.rs$

      # Cargo Clippy linting
      - id: cargo-clippy
        name: Cargo Clippy
        language: system
        entry: cargo
        args:
          [
            "clippy",
            "--all",
            "--tests",
            "--all-features",
            "--no-deps",
            "--",
            "-D",
            "warnings",
          ]
        pass_filenames: false

      # Cargo deny check
      - id: cargo-deny
        name: Cargo Deny
        language: system
        entry: cargo
        args: ["deny", "check"]
        pass_filenames: false

      # Link validation
      - id: lychee
        name: Lychee
        language: system
        entry: lychee
        args: ["--no-progress", "--cache"]

  # [WON'T WORK !!!]
  #  - repo: https://github.com/lycheeverse/lychee.git
  #    rev: v0.15.1
  #    hooks:
  #      - id: lychee
  #        args: ["--no-progress", "--cache"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
