repos:
  - repo: local
    hooks:
      # Rustfmt formatting check
      - id: rustfmt
        name: Rustfmt
        language: system
        entry: rustfmt
        args: ["--edition", "2024", "--check"]
        pass_filenames: true
        files: \.rs$

      # Cargo Clippy linting
      - id: cargo-clippy
        name: Cargo Clippy
        language: system
        entry: cargo
        args:
          [
            "clippy",
            "--all",
            "--tests",
            "--all-features",
            "--no-deps",
            "--",
            "-D",
            "warnings",
          ]
        pass_filenames: false

      # Cargo deny check
      - id: cargo-deny
        name: Cargo Deny
        language: system
        entry: cargo
        args: ["deny", "check"]
        pass_filenames: false

      # Markdown linting
      - id: markdownlint
        name: Markdownlint
        language: node
        entry: npx
        args:
          - markdownlint
          - "--ignore"
          - "node_modules"
        pass_filenames: true
        files: \.md$

      # Link validation
      - id: lychee
        name: Lychee
        language: system
        entry: lychee
        args: ["--no-progress", "--cache"]
