[workspace]
members = ["implementations/*", "utilities/bench_util", "utilities/cache_util"]

# tells Cargo to use the newer dependency resolver,
# which aligns with Rust 2021 edition and ensures compatibility with its features
resolver = "2"
