# https://embarkstudios.github.io/cargo-deny/cli/init.html

[graph]
all-features = true

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0"]
exceptions = [
    { allow = [
        "LGPL-3.0-or-later",
        "MPL-2.0",
    ], crate = "priority-queue" },
    { allow = [
        "(Apache-2.0 OR MIT) AND BSD-3-Clause",
    ], crate = "encoding_rs" },
]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
