#!/usr/bin/env bash

# [Run before committing via hook]
# ln -s ../../utilities/pre-commit .git/hooks/

set -e  # Exit on error

rustfmt --check --edition 2024 $(git ls-files '*.rs')

cargo clippy --all --tests --all-features --no-deps

markdownlint '**/*.md' --ignore node_modules