pub struct Solution;

// Generated by ChatGPT o1-preview, which is both clean and concise, AWESOME!

impl Solution {
    // https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
    // pub fn merge(nums1: &mut Vec<i32>, m: i32, nums2: &mut Vec<i32>, n: i32)

    pub fn merge(nums1: &mut [i32], m: usize, nums2: &[i32], n: usize) {
        let mut i = m;
        let mut j = n;
        let mut k = m + n;

        while j > 0 {
            if i > 0 && nums1[i - 1] > nums2[j - 1] {
                nums1[k - 1] = nums1[i - 1];
                i -= 1;
            } else {
                nums1[k - 1] = nums2[j - 1];
                j -= 1;
            }
            k -= 1;
        }
    }
}
