name: "Basic Checks"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/elapsed-time
      with:
        statement: "actions/checkout"

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.rust_nightly }}
        components: clippy, rustfmt

    - uses: ./.github/actions/elapsed-time
      with:
        statement: "rust-toolchain"

    - uses: Swatinem/rust-cache@v2

    - uses: ./.github/actions/elapsed-time
      with:
        statement: "rust-cache"

    - name: Install cargo-deny
      uses: ./.github/actions/install-from-tarball
      with:
        url: "https://github.com/EmbarkStudios/cargo-deny/releases/download/0.16.3/cargo-deny-0.16.3-x86_64-unknown-linux-musl.tar.gz"
        executable: "cargo-deny"
        target_path: "$CARGO_HOME/bin"

    - uses: ./.github/actions/elapsed-time
      with:
        statement: "Install cargo-deny"

    - name: Install lychee
      uses: ./.github/actions/install-from-tarball
      with:
        url: "https://github.com/lycheeverse/lychee/releases/download/lychee-v0.18.0/lychee-x86_64-unknown-linux-musl.tar.gz"
        executable: "lychee"
        target_path: "$CARGO_HOME/bin"

    - uses: ./.github/actions/elapsed-time
      with:
        statement: "Install lychee"

    - name: Restore lychee cache
      uses: actions/cache@v4
      with:
        path: .lycheecache
        key: cache-lychee-${{ github.sha }}
        restore-keys: cache-lychee-

    - uses: ./.github/actions/elapsed-time
      with:
        statement: "Restore lychee cache"

    - name: Run pre-commit
      run: |
        time python3 -m venv venv
        time source venv/bin/activate
        time pip -q install pre-commit
        time pre-commit run --all-files
      shell: bash

    - uses: ./.github/actions/elapsed-time
      with:
        statement: "pre-commit"

inputs:
  rust_nightly:
    description: "Rust nightly toolchain version"
    required: false
    default: "nightly"
