name: Pull Request Security Audit

on:
  push:
    paths:
      - "**/Cargo.toml"
  pull_request:
    paths:
      - "**/Cargo.toml"

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  rust_nightly: nightly-2024-12-02

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.rust_nightly }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_nightly }}
      - uses: EmbarkStudios/cargo-deny-action@v2
