name: PR Checks

on:
  pull_request:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  rust_nightly: nightly-2024-12-02

jobs:
  basics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/basics
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rust_nightly: ${{ env.rust_nightly }}
