name: PR Checks

on:
  pull_request:

jobs:
  basics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/basics
        with:
          rust_nightly: nightly-2024-12-02
