name: PR Checks

on:
  pull_request:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  rust_nightly: nightly-2024-12-02

defaults:
  run:
    shell: bash

jobs:
  basics:
    runs-on: ubuntu-latest
    env:
      GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/basics
        with:
          rust_nightly: ${{ env.rust_nightly }}
